export const ACTION_TYPES = {
  SCROLL_START: "SCROLL_START",
  SCROLL_STOP: "SCROLL_STOP",
  SET_SCROLL_LEFT: "SET_SCROLL_LEFT",
  SET_SCROLL_TOP: "SET_SCROLL_TOP",
  REQUEST_SCROLL_UPDATE: "REQUEST_SCROLL_UPDATE",
  DENY_SCROLL_UPDATE: "DENY_SCROLL_UPDATE",
  CLEAR_CELL_CACHE: "CLEAR_CELL_CACHE",
  CLEAR_CELLSTYLE_CACHE: "CLEAR_CELLSTYLE_CACHE",
  CLEAR_ROWSTYLE_CACHE: "CLEAR_ROWSTYLE_CACHE",
  GET_CELL: "GET_CELL",
  GET_ROWSTYLE: "GET_ROWSTYLE",
};
